contact_list/config/routes.rb
Rails.application.routes.draw do

   root 'home#index'

     resources :contacts

end

contact_list/app/models/contact.rb
class Contact < ActiveRecord::Base
end

contact_list/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

contact_list/app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def show
    @contact = Contact.find params[:id]
  end

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.create que_params
    redirect_to root_path
  end

  def edit
    @contact = Contact.find params[:id]
  end

  def update
    @contact = Contact.find params[:id]
    @contact.update_attributes que_params
    redirect_to root_path
  end

  def destroy
    @contact = Contact.find params[:id]
    @contact.delete
    redirect_to root_path
  end

private
  def que_params
    params.require(:contact).permit(:name)
  end
end

contact_list/app/controllers/home_controller.rb
class HomeController < ApplicationController
def index
	@contacts = Contact.all
end
end

contact_list/app/helpers/application_helper.rb
module ApplicationHelper
end

contact_list/app/helpers/contacts_helper.rb
module ContactsHelper
end

contact_list/app/helpers/home_helper.rb
module HomeHelper
end

contact_list/app/views/contacts/edit.html.erb
<h1>Edit Contact</h1>
<%= form_for @contact do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br>
  <%= f.submit %>
<% end %>

contact_list/app/views/contacts/new.html.erb
<h1>New Contact</h1>

<%= form_for @contact do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br>
  <%= f.submit %>
<% end %>

contact_list/app/views/contacts/show.html.erb
<h1>Show data</h1>

<%= @contact.name %>

<%= link_to "Home", root_path %>

contact_list/app/views/home/index.html.erb
<h1>The Blog that never blogs!</h1>

<%= link_to "Create Post", new_contact_path %>
<br>
<% @contacts.each do |contact| %>
  <%= link_to contact.name, contact_path(contact) %>
  <%= link_to "Edit", edit_contact_path(contact) %>
  <%= link_to "Delete", contact_path(contact), method: :delete %>
  <br>
<% end %>

contact_list/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ContactList</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>